### ISSUE TITLE
Installation details in README.md

### ISSUE THREAD

**Issue by spinicist** [neurodata/neuroparc#26]
Hello,

Thanks for gathering all these atlases in one place. It's very handy.

I naively attempted to download the atlases via the "Download as Zip" button on Github. This doesn't work due to the use of `git-lfs`. Perhaps the `README.md` should start with details of how to obtain the atlases via `git clone` and explain why?

Also, at the end of cloning, my version of `git-lfs` reported that two files "were not pointers, but should have been".

**Comment by ofgulban** [comment]
I totally agree with @spinicist , had the same issue. Having a "how to download atlases" section in the readme would reduce confusion (e.g. see #35, #36 ).
