### ISSUE TITLE
Atlas Summary

### ISSUE THREAD

**Issue by GaneshArvapalli** [neurodata/neuroparc#3]
I think it would be helpful to organize the information about each of the atlases in this repo. I would like to see a table with a row for each atlas and each column in that row containing some statistics about the atlas. This would make it easy to compare information about different atlases and maybe there would be some that suit specific purposes that people could identify. Ex:

|  | Volume | Labels | Center | etc... |
|---------|---------|--------|-------|------|
| Atlas 1 |    |    |    |
| Atlas 2 |    |    |    |
| ... |    |    |    |

**Comment by jovo** [comment]
Do it!
