### ISSUE TITLE
can not open any atlases or nifti images using MRIcron or ITKsnap

### ISSUE THREAD

**Issue by garincle** [neurodata/neuroparc#35]
Not sure why but I can not open any atlases or nifti templates using MRIcron or ITKsnap
I have got with ITKsnap:

Error: Unsupported or missing image file format. ITK-SNAP failed to create an ImageIO object for the image 'neuroparc-master/atlases/label/Human/AAL_space-MNI152NLin6_res-2x2x2.nii.gz' using format ''.

**Comment by ofgulban** [comment]
I had the same issue when cloning the github repository. However, reading the paper, the atlas niftis can be downloaded from the OSF page: <https://osf.io/67a3t/>

See the folder below:
![Screenshot_2021-09-15_13-42-44](https://user-images.githubusercontent.com/4668327/133427278-4881354a-e13d-45a8-a5f0-7186bf3b1c95.png)

@neuroparc creators/maintainers, thanks for making this project, quite useful to have all these atlases organized so neatly :)

**Comment by Remi-Gau** [comment]
@ofgulban 
Sounds like a better option to turn this repo into a datalad dataset hosted on GIN, no?
