### ISSUE TITLE
Cannot open atlases nor metadata

### ISSUE THREAD

**Issue by GGonEsc** [neurodata/neuroparc#36]
AFter downloading, each file only contains github version, ID and size. Example of the AAL atlas in: https://github.com/neurodata/neuroparc/blob/master/atlases/label/Human/AAL_space-MNI152NLin6_res-1x1x1.nii.gz

version https://git-lfs.github.com/spec/v1
oid sha256:020f4a0d7bee976d910ca2c9ff19adab7f34facaa60909d1cbbccaecd83a5de1
size 29680

When this should be a compresssed nifti file.
The exact same information is contained in the cvs and json metadata files.

**Comment by ofgulban** [comment]
Hey, I had the same issue and found a solution. See my comment on another similar issue: https://github.com/neurodata/neuroparc/issues/35#issuecomment-919946502

**Comment by Lawreros** [comment]
Thanks for the feedback! Haven't checked on this repo in a bit, but I'll be fixing this soon.

**Comment by Lawreros** [comment]
We've updated our account, the repo should be downloadable now
