### ISSUE TITLE
datalad fork of the data content

### ISSUE THREAD

**Issue by Remi-Gau** [neurodata/neuroparc#38]
I created a datalad dataset to store the data content of this repo and to get around the GIT LFS issues mentionned (#36, #35, #26)

https://gin.g-node.org/cpp-lln-lab/neuroparc_data

**Comment by Remi-Gau** [comment]
Ideally it should be added as a submodule to replace the current `atlas` folder.

**Comment by Remi-Gau** [comment]
I created a datalad branch on my fork and set up the data as submodule and all the things should be accessible by doing

```
datalad install -r https://github.com/Remi-Gau/neuroparc.git
```

**Comment by Remi-Gau** [comment]
FYI: more than happy to show you how to set up your own data repo on GIN so you can host the data yourself.

**Comment by Lawreros** [comment]
Thanks for that @Remi-Gau . We've updated our git account so the repo should be downloadable again.
