### ISSUE TITLE
Cannot work out file type

### ISSUE THREAD

**Issue by natalier11** [neurodata/neuroparc#41]
Hi there!

I'm trying to run the DICE correlation between the 1x1x1 Destrieux and the 1x1x1 Yeo 7 liberal atlases in a jupyter notebook and I'm running into an issue in the fourth cell. I keep getting the following error:
![Cell4Error](https://user-images.githubusercontent.com/73397911/153928669-083a5d56-7d0a-4b1f-9541-5aa6cd7f265a.png)
I have copied the atlas names exactly (with the MNI152NLin6 and the .nii.gz) and am pretty positive that the input directory is correct. I was also able to successfully import nibabel, numpy, argparse, and matplotlib in the first cell. Let me know if there's something else I need to be doing to move forward with the correlation, thanks!

**Comment by Lawreros** [comment]
Hi @natalier11 ,
Are you able to open the atlas files with something like FLSeyes? You may have pulled the pointer file related to git-lfs (something I think I just fixed today).
