### ISSUE TITLE
Add fields to all json specifications

### ISSUE THREAD

**Issue by ebridge2** [neurodata/neuroparc#6]
Many of the jsons for different parcellations already have labels pre-computed, but it would be of value to ensure that all have fields for "parcel name", "Hemisphere" (L/R), "Tissue Type" (GM, WM, CSF), "Yeo7 Network" (1 -> 7) "Center of Mass" ([a,b,c], in mms), lobe pre-computed for all parcellations.

**Comment by jovo** [comment]
+1

**Comment by ebridge2** [comment]
https://github.com/neurodata/neuroparc/blob/master/scripts/centers.py for centers

https://github.com/neurodata/vertex-contract/blob/master/scripts/DS-anat/DS-anat.ipynb for computing maximal overlap (just replace DS_atlases with all of the parcellations, anat_atlases with the tissue, hemisphere, and lobe parcellations, and then  output in the desired JSON formatting)

you should be able to largely just merge these two scripts/notebooks and just output as json to acquire the desired results
